namm: About - Thanos Theodoridis - Software Engineer
description: Hello. I am Thanos. Node.js, Angular and iOS hacker. UX/UI Designer. Generalist, full-stack, real deal. I like startups, beer and women.

url: http://localhost:8080

paginate: 10

markdown: rdiscount
permalink: pretty
highligther: pygments
